27-rails-auth-part2/config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:show, :new, :index, :create]
  root 'students#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy', as: :logout
  resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

27-rails-auth-part2/app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
end

27-rails-auth-part2/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort, optional: true

  validates :name, :email, presence: true
  validates :email, uniqueness: true

end

27-rails-auth-part2/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, {presence: true, uniqueness: true}

  # passsword=()
  # password_confirmation=()
end

27-rails-auth-part2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  before_action :set_current_user

  def set_current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!@current_user
  end
end

27-rails-auth-part2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to students_path
    else
      flash[:message] = 'Invalid Login'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to students_path
  end

end

27-rails-auth-part2/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    if logged_in?
      @student = Student.new
    else
      flash[:message] = 'Login Sucka'
      redirect_to login_path
    end
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end

  end

  private
  def student_params
    params.require(:student).permit(:name, :email, :cohort_id)
  end
end

27-rails-auth-part2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    byebug
    user = User.new(user_params)
    if user.valid?
      user.save
      session[:user_id] = user.id
      redirect_to students_path
    else
      # flash[:message] = 'Nice try, buddy'
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

27-rails-auth-part2/app/helpers/application_helper.rb
module ApplicationHelper
end

27-rails-auth-part2/app/helpers/students_helper.rb
module StudentsHelper
end

27-rails-auth-part2/app/helpers/users_helper.rb
module UsersHelper
end

27-rails-auth-part2/app/views/students/index.html.erb
<h1>All Students</h1>

<div class= 'ui huge middle aligned selection divided list'>
  <% @students.each do |student| %>
    <div class="item">
      <%= link_to student.name, student_path(student) %>
    </div>
  <% end %>
</div>

27-rails-auth-part2/app/views/students/new.html.erb
<h1>Create a Student</h1>

<%= form_for @student, html: {class: 'ui form'} do |f| %>
  <div class="field">
    <%= f.text_field(:name, placeholder: 'Enter the student name...') %>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: 'Enter the student email...' %>
  </div>
  <div class="field">
    <%= f.collection_select(:cohort_id, Cohort.all, :id, :name) %>
  </div>
  <%= f.submit({class: 'ui huge pink button'}) %>
<% end %>

27-rails-auth-part2/app/views/students/show.html.erb
<div class='ui raised segment'>
  <div class='ui fluid card'>
    <div class='huge content'>
      <div class='header'><h1><%= @student.name %></h1></div>
      <div class="meta">
         <span class="date">
           <h3><%= @student.cohort.name %> (<%= @student.cohort.start_date.strftime('%m%d%y') %>)</h3>
         </span>
      </div>
      <div class="description">
        <h3><%= @student.email %></h3>
      </div>
    </div>
  </div>
</div>