23-rails-brews-crew-review/erin/brews-crew/config/routes.rb
Rails.application.routes.draw do
  resources :purchases, only: [:new, :create, :index, :show]
  get 'brews/strongest', to: 'brews#strongest', as: 'strongest_view'
  resources :brews

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

23-rails-brews-crew-review/erin/brews-crew/app/models/brew.rb
class Brew < ApplicationRecord
  has_many :purchases
  validates :blend_name, uniqueness: true

  def self.strongest
    max_strength = self.maximum(:strength)
    self.where(strength: max_strength)
  end

  def customer_names
    # self.purchases.map { |p| p.customer_name }.uniq
    self.purchases.pluck(:customer_name).uniq
  end
end

23-rails-brews-crew-review/erin/brews-crew/app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :brew
  # validates :size, inclusion: {in: %w(small medium large)}
  validates :size, inclusion: {in: ["small", "medium", "large"]}
  validates :special_instructions, length: {maximum: 140}

  # def blend_name
  #   self.brew.blend_name
  # end
end

23-rails-brews-crew-review/erin/brews-crew/app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  def index
    @brews = Brew.all
  end

  def show
    @brew = Brew.find(params[:id])
  end

  def destroy
    Brew.destroy(params[:id])
    redirect_to brews_path
  end

  def new
    @brew = Brew.new
  end

  def create
    @brew = Brew.create(brew_params)
    redirect_to @brew
  end

  def edit
    @brew = Brew.find(params[:id])
  end

  def update
    @brew = Brew.find(params[:id])
    @brew.update(brew_params)
    redirect_to @brew
  end

  def strongest
    @strongest_brews = Brew.strongest
  end

  private

  def brew_params
    params.require(:brew).permit(:blend_name, :origin, :notes, :strength)
  end

  # t.string "blend_name"
  # t.string "origin"
  # t.string "notes"
  # t.integer "strength"
end

23-rails-brews-crew-review/erin/brews-crew/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.create(purchase_params)
    redirect_to purchases_path
  end

  def index
    @purchases = Purchase.all
  end

  def show
    @purchase = Purchase.find(params[:id])
    @brew = @purchase.brew
  end

  private

  def purchase_params
    params.require(:purchase).permit! # <-- unsafe but we're lazy
  end
end

23-rails-brews-crew-review/erin/brews-crew/app/helpers/brew_helper.rb
module BrewHelper
end

23-rails-brews-crew-review/erin/brews-crew/app/views/brews/edit.html.erb
<h1>Brew#edit</h1>
<%= form_for @brew do |f| %>
  <%= f.label :blend_name %><%= f.text_field :blend_name %><br>
  <%= f.label :origin %><%= f.text_field :origin %><br>
  <%= f.label :notes %><%= f.text_field :notes %><br>
  <%= f.select(:strength, 1..5) %><br>

  <%= f.submit %>
<% end %>

23-rails-brews-crew-review/erin/brews-crew/app/views/brews/index.html.erb
<h1>Brews#index</h1>

<% @brews.each do |brew| %>
  <%= link_to(brew.blend_name, brew) %> <%= link_to("Delete", brew, {method: :delete})%><br>
<% end %>

<br>
<%= link_to "View strongest brew(s)", strongest_view_path %>

23-rails-brews-crew-review/erin/brews-crew/app/views/brews/new.html.erb
<h1>Brew#new</h1>
<%= form_for @brew do |f| %>
  <%= f.label :blend_name %><%= f.text_field :blend_name %><br>
  <%= f.label :origin %><%= f.text_field :origin %><br>
  <%= f.label :notes %><%= f.text_field :notes %><br>
  <%= f.select(:strength, 1..5) %><br>

<!-- <select name="brew[strength]" id="brew_strength"><option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option></select><br> -->

  <%= f.submit %>
<% end %>

<%# t.string "blend_name"
t.string "origin"
t.string "notes"
t.integer "strength" %>

23-rails-brews-crew-review/erin/brews-crew/app/views/brews/show.html.erb
<h1><%= @brew.blend_name %></h1>

Origin: <%= @brew.origin %><br>
Notes: <%= @brew.notes %><br>
Strength: <%= @brew.strength %><br>

Customers: <%= @brew.customer_names %>

<%# t.string "blend_name"
t.string "origin"
t.string "notes"
t.integer "strength" %>

23-rails-brews-crew-review/erin/brews-crew/app/views/brews/strongest.html.erb
<h1>Brew#strongest</h1>
<% @strongest_brews.each do |sb| %>
  <%= sb.blend_name %><br>
<% end %>