23-rails-brews-crew-review/greg/brews-crew/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/brews/strongest', to: 'brews#strongest'
  resources :brews
  resources :purchases
end

23-rails-brews-crew-review/greg/brews-crew/app/models/brew.rb
# frozen_string_literal: true

class Brew < ActiveRecord::Base
  has_many :purchases

  
end

23-rails-brews-crew-review/greg/brews-crew/app/models/purchase.rb
# frozen_string_literal: true

class Purchase < ActiveRecord::Base
  belongs_to :brew
end

23-rails-brews-crew-review/greg/brews-crew/app/controllers/brews_controller.rb
# frozen_string_literal: true

class BrewsController < ApplicationController
  def index
    @brews = Brew.all
  end

  def show
    set_brews
  end

  def new
    @brew = Brew.new
  end

  def create
    @brew = Brew.new(brew_params)
    if @brew.save
      redirect_to @brew
    else
      render :new
    end
  end

  def destroy
    set_brews
    @brew.destroy
    redirect_to brews_path
  end

  def edit
    set_brews
  end

  def update
    set_brews
    if @brew.update(brew_params)
      redirect_to @brew
    else
      render :edit
    end
  end

  def strongest
    @brews = Brew.where(strength: Brew.maximum(:strength))
  end

  private

  def set_brews
    @brew = Brew.find(params[:id])
  end

  def brew_params
    params.require(:brew).permit(:blend_name, :origin, :notes, :price, :strength)
  end
end

23-rails-brews-crew-review/greg/brews-crew/app/controllers/purchases_controller.rb
# frozen_string_literal: true

class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.all
    end

  def show
    set_purchases
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(purchase_params)
    if @purchase.save
      redirect_to @purchase
    else
      render :new
    end
  end

  def destroy
    set_purchases
    @purchase.destroy
    redirect_to purchases_path
  end

  def edit
    set_purchases
  end

  def update
    set_purchases
    if @purchase.update(purchase_params)
      redirect_to @purchase
    else
      render :edit
    end
  end

  private

  def set_purchases
    @purchase = Purchase.find(params[:id])
  end

  def purchase_params
    params.require(:purchase).permit(:customer)
  end
end

23-rails-brews-crew-review/greg/brews-crew/app/helpers/brews_helper.rb
module BrewsHelper
end

23-rails-brews-crew-review/greg/brews-crew/app/helpers/purchases_helper.rb
module PurchasesHelper
end

23-rails-brews-crew-review/greg/brews-crew/app/views/brews/_form.html.erb
<%= form_for(@brew) do |f| %>
    <%= f.label :blend_name %>
    <%= f.text_field :blend_name %><br>
    <%= f.label :origin %>
    <%= f.text_field :origin %><br>
    <%= f.label :notes %>
    <%= f.text_field :notes %><br>
    <%= f.label :price %>
    <%= f.text_field :price %><br>
    <%= f.label :strength %>
    <%= f.text_field :strength %><br>
    <%= f.submit %>
<% end %>

23-rails-brews-crew-review/greg/brews-crew/app/views/brews/edit.html.erb
<%= render 'form' %>

23-rails-brews-crew-review/greg/brews-crew/app/views/brews/index.html.erb
<h1>View all Brews</h1>

<% @brews.each do |brew|%>
    <%= link_to brew.blend_name, brew_path(brew) %> | 
    <%= link_to "Delete" , brew, method: "delete", data: { confirm: "Are you sure?"} %><br>
<% end %>

23-rails-brews-crew-review/greg/brews-crew/app/views/brews/new.html.erb
<%= render 'form' %>

23-rails-brews-crew-review/greg/brews-crew/app/views/brews/show.html.erb
<h1>Show a Brew</h1>

Blend Name: <%= @brew.blend_name %><br>
<%= @brew.origin %><br>
<%= @brew.notes %><br>
<%= @brew.price %><br>
<%= @brew.strength %>

23-rails-brews-crew-review/greg/brews-crew/app/views/brews/strongest.html.erb
<h1>Strongest Brews</h1>

<%@brews.each do |brew| %>
    <%= link_to brew.blend_name, brew_path(brew) %>
<% end%>

23-rails-brews-crew-review/greg/brews-crew/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewsCrew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

23-rails-brews-crew-review/greg/brews-crew/app/views/purchases/new.html.erb
<%= form_for(@purchase) do |f| %>
    <%= f.label :customer %>
    <%= f.text_field :customer %>
    <%= f.label :brews %>
    <%= f.check_box() %>
    <%= f.check_box( ) %>
<% end %>
 <%# the new page should allow you to choose the brews that were purchased (with checkboxes), the customer who made the purchase (with a drop-down), and the price of the purchase (with a textbox) %>